# dist: trusty
# sudo: false
 
# language: node_js
# node_js:
#   - "8"
  
# addons:
#   apt:
#     sources:
#       - google-chrome
#     packages:
#       - google-chrome-stable
 
# cache:
#   directories:
#      - ./my-app/node_modules
 
# install:
#   - cd my-app
#   - npm install
 
# script:
#   - npm run lint
#   - npm run testCI
# #  - npm run test --no-watch --no-progress --browsers=ChromeHeadlessCI
# #  - npm run e2e --protractor-config=e2e/protractor-ci.conf.js

language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
script:
    - cd source/
    - dotnet restore
    - dotnet build  
    - dotnet test ../UnitTest/UnitTests.csproj

#  language: csharp
# dist: trusty
# mono: none
# dotnet: 1.0.1
# install:
# - dotnet restore
# script:
# - dotnet build
# - dotnet test Core.Shogi.Tests/Core.Shogi.Tests.csproj